import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: "long-way-home",
    title: "The Long Way Home",
    category: "Script",
    type: "YouTube Documentary",
    description: "A 4-part documentary series about identity, migration, and starting over.",
    image: "/images/work/long-way-home.jpg",
    href: "/blog/long-way-home",
    featured: true,
  },
  {
    id: "nomad-goods",
    title: "Nomad Goods",
    category: "Copy",
    type: "Website Copy",
    image: "/images/work/nomad.jpg",
    href: "/blog/nomad-goods",
  },
  {
    id: "focus-journal",
    title: "The Focus Journal",
    category: "Copy",
    type: "Founder’s Letter",
    image: "/images/work/focus-journal.jpg",
    href: "/blog/focus-journal",
  },
  {
    id: "what-makes-us-human",
    title: "What Makes Us Human",
    category: "Script",
    type: "YouTube Script",
    image: "/images/work/human.jpg",
    href: "/blog/what-makes-us-human",
  },
  {
    id: "brand-campaign",
    title: "Brand Campaign",
    category: "Copy",
    type: "Launch Copy",
    image: "/images/work/campaign.jpg",
    href: "/blog/brand-campaign",
  },
  {
    id: "ten-ideas",
    title: "Ten Ideas Worth Remembering",
    category: "Essay",
    type: "Long-Form Essay",
    image: "/images/work/essay.jpg",
    href: "/blog/ten-ideas",
  },
  {
    id: "nonfiction-manuscript",
    title: "Nonfiction Manuscript",
    category: "Edit",
    type: "Developmental Edit",
    image: "/images/work/manuscript.jpg",
    href: "/blog/nonfiction-manuscript",
  },
];
